import userImg from "../../../assets/images/user.png";

export const ChatListData = [
  {
    id: 1,
    userImg: userImg,
    userName: "김특허1 변리사",
    writedAt: "2023.12.04 14:14",
    msg: "안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요",
    file: "생활-기타 : 식물 자동 급수를 위한 장치와 그 방법",
  },
  {
    id: 2,
    userImg: userImg,
    userName: "김특허2 변리사",
    writedAt: "2021.09.01 14:14",
    msg: "안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요",
    file: "생활-기타 : 식물 자동 급수를 위한 장치와 그 방법",
  },
  {
    id: 3,
    userImg: userImg,
    userName: "김특허3 변리사",
    writedAt: "2021.09.01 14:14",
    msg: "안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요",
    file: "생활-기타 : 식물 자동 급수를 위한 장치와 그 방법",
  },
  {
    id: 4,
    userImg: userImg,
    userName: "김특허4 변리사",
    writedAt: "2021.09.01 14:14",
    msg: "안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요",
    file: "생활-기타 : 식물 자동 급수를 위한 장치와 그 방법",
  },
  {
    id: 5,
    userImg: userImg,
    userName: "김특허5 변리사",
    writedAt: "2021.09.01 14:14",
    msg: "안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요",
    file: "생활-기타 : 식물 자동 급수를 위한 장치와 그 방법",
  },
  {
    id: 6,
    userImg: userImg,
    userName: "김특허6 변리사",
    writedAt: "2021.09.01 14:14",
    msg: "안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요",
    file: "생활-기타 : 식물 자동 급수를 위한 장치와 그 방법",
  },
  {
    id: 7,
    userImg: userImg,
    userName: "김특허6 변리사",
    writedAt: "2021.09.01 14:14",
    msg: "안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요",
    file: "생활-기타 : 식물 자동 급수를 위한 장치와 그 방법",
  },
  {
    id: 8,
    userImg: userImg,
    userName: "김특허6 변리사",
    writedAt: "2021.09.01 14:14",
    msg: "안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요안녕하세요",
    file: "생활-기타 : 식물 자동 급수를 위한 장치와 그 방법",
  },
];

export const ChatContentsData = [
  {
    id: 1,
    userImg: userImg,
    userName: "나",
    writedAt: "2023.12.04 14:14",
    msg: "안녕하세요. 식물 자동 급수를 위한 특허를 준비하고 있습니다.",
  },
  {
    id: 2,
    userImg: userImg,
    userName: "나",
    writedAt: "2023.12.04 14:14",
    msg: "기존에 보낸 자료는 보셨나요",
  },
  {
    id: 3,
    userImg: userImg,
    userName: "김특허1 변리사",
    writedAt: "2023.12.04 14:14",
    msg: "안녕하세요",
  },
  {
    id: 4,
    userImg: userImg,
    userName: "김특허1 변리사",
    writedAt: "2023.12.04 14:14",
    msg: "자료 확인했습니다.",
  },
  {
    id: 5,
    userImg: userImg,
    userName: "김특허1 변리사",
    writedAt: "2023.12.04 14:14",
    msg: "감사합니다.",
  },
];
